workspace 'MobileMetricaSample.xcworkspace'
project 'MobileMetricaSample.xcodeproj'
platform :ios, '15.0'

target :MobileMetricaSample do
    project 'MobileMetricaSample.xcodeproj'
    pod 'YandexMobileMetrica', '4.0.0'
end

target :MobileMetricaSampleToday do
    project 'MobileMetricaSample.xcodeproj'
    pod 'YandexMobileMetrica', '4.0.0'
end